# Enable AndroidX and Jetpack Compose compiler support
android.useAndroidX=true
android.enableJetifier=true

# Optimize Gradle build performance
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# Suppress Non-transitive R class warnings
android.nonTransitiveRClass=true
